//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteIO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prompt
    {
        public int PromptID { get; set; }
        public string PromptContent { get; set; }
        public string Author { get; set; }
        public string Category { get; set; }
    }
}
