//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteIO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionID { get; set; }
        public string Author { get; set; }
        public System.DateTime WrittenDate { get; set; }
        public int Upvotes { get; set; }
        public int Downvotes { get; set; }
        public int SequenceNumber { get; set; }
        public int StoryID { get; set; }
        public string SectionContent { get; set; }
        public bool IsCommitted { get; set; }
    }
}
