//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteIO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int StoryID { get; set; }
        public int PromptID { get; set; }
        public int SectionID { get; set; }
    }
}
